"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import localFont from "@next/font/local";
import "@rainbow-me/rainbowkit/styles.css";
import { Providers } from "./providers";
import { Poppins } from "next/font/google";
import { Montserrat } from "next/font/google";

const myFont = localFont({ src: "./BrantFord.woff2" });
const poppins = Poppins({   weight: ['400','600','800'],
subsets: ['latin'] })

// export const metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={myFont.className}>
                <Providers>{children}</Providers>
            </body>
        </html>
    );
}
