"use client";
import { Inter } from "next/font/google";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });
import localFont from "@next/font/local";
import "@rainbow-me/rainbowkit/styles.css";
import { Providers } from "./providers";

const myFont = localFont({ src: "./King-Gaming.woff2" });

// export const metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={myFont.className}>
                <Providers>{children}</Providers>
            </body>
        </html>
    );
}
